"""
StreamForge data models.

Defines the Pydantic models used by:
- telemetry producers
- stream workers
- windowed aggregation
- worker metrics
- checkpoint/recovery
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class TelemetryEvent(BaseModel):
    """
    Telemetry event produced by StreamForge devices.

    The schema intentionally matches the payload generated by producer.py.
    """

    model_config = ConfigDict(extra="forbid")

    event_id: str = Field(min_length=1)
    device_id: str = Field(min_length=1)
    timestamp: datetime

    temperature: float
    humidity: float
    pressure: float
    battery: float
    sequence: int = Field(ge=0)

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, value: datetime) -> datetime:
        """Ensure timestamps are timezone-aware."""

        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)

        return value

    @field_validator("humidity")
    @classmethod
    def validate_humidity(cls, value: float) -> float:
        """Validate relative humidity."""

        if not 0.0 <= value <= 100.0:
            raise ValueError("humidity must be between 0 and 100")

        return value

    @field_validator("battery")
    @classmethod
    def validate_battery(cls, value: float) -> float:
        """Validate battery percentage."""

        if not 0.0 <= value <= 100.0:
            raise ValueError("battery must be between 0 and 100")

        return value


class TemperatureAggregate(BaseModel):
    """
    Aggregated temperature statistics for a device/window.
    """

    model_config = ConfigDict(extra="forbid")

    aggregate_id: str = Field(min_length=1)
    device_id: str = Field(min_length=1)

    window_start: datetime
    window_end: datetime

    event_count: int = Field(ge=0)

    temperature_sum: float = 0.0
    temperature_min: float | None = None
    temperature_max: float | None = None
    temperature_avg: float | None = None

    last_event_timestamp: datetime | None = None

    @field_validator("window_start", "window_end", "last_event_timestamp")
    @classmethod
    def validate_datetime(
        cls,
        value: datetime | None,
    ) -> datetime | None:
        """Ensure datetime values are timezone-aware."""

        if value is None:
            return None

        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)

        return value


class WorkerMetric(BaseModel):
    """
    Runtime metrics reported by a StreamForge worker.
    """

    model_config = ConfigDict(extra="forbid")

    worker_id: str = Field(min_length=1)
    timestamp: datetime

    messages_processed: int = Field(ge=0)
    messages_failed: int = Field(ge=0)

    events_per_second: float = Field(ge=0.0)
    processing_latency_ms: float = Field(ge=0.0)

    partitions_assigned: int = Field(ge=0)
    active_windows: int = Field(ge=0)

    bytes_processed: int = Field(default=0, ge=0)

    status: str = "running"

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, value: datetime) -> datetime:
        """Ensure timestamp is timezone-aware."""

        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)

        return value


class CheckpointMetadata(BaseModel):
    """
    Metadata describing a worker checkpoint.
    """

    model_config = ConfigDict(extra="forbid")

    checkpoint_id: str = Field(min_length=1)
    worker_id: str = Field(min_length=1)

    created_at: datetime

    state_path: str = Field(min_length=1)

    event_count: int = Field(default=0, ge=0)

    topic: str | None = None
    partitions: list[int] = Field(default_factory=list)

    offsets: dict[str, int] = Field(default_factory=dict)

    state_size_bytes: int = Field(default=0, ge=0)

    @field_validator("created_at")
    @classmethod
    def validate_created_at(cls, value: datetime) -> datetime:
        """Ensure checkpoint timestamp is timezone-aware."""

        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)

        return value


# Backwards-compatible aliases used by earlier StreamForge modules/tests.
Aggregate = TemperatureAggregate
Checkpoint = CheckpointMetadata


def _producer_payload_test() -> dict[str, Any]:
    """
    Return a payload matching producer.py.

    This is used by the module self-test to make sure the producer and
    worker schemas remain compatible.
    """

    return {
        "event_id": "test-event-001",
        "device_id": "device-001",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "temperature": 25.5,
        "humidity": 60.0,
        "pressure": 1013.25,
        "battery": 95.0,
        "sequence": 1,
    }


def run_self_test() -> None:
    """Run a lightweight model validation self-test."""

    print("StreamForge models self-test")
    print("-" * 60)

    # ------------------------------------------------------------------
    # TelemetryEvent
    # ------------------------------------------------------------------

    payload = _producer_payload_test()

    event = TelemetryEvent.model_validate(payload)

    assert event.event_id == "test-event-001"
    assert event.device_id == "device-001"
    assert event.temperature == 25.5
    assert event.humidity == 60.0
    assert event.pressure == 1013.25
    assert event.battery == 95.0
    assert event.sequence == 1

    print("TelemetryEvent validation: OK")
    print("Producer payload compatibility: OK")

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    serialized = event.model_dump()

    assert serialized["event_id"] == "test-event-001"
    assert serialized["device_id"] == "device-001"
    assert serialized["humidity"] == 60.0
    assert serialized["pressure"] == 1013.25
    assert serialized["battery"] == 95.0
    assert serialized["sequence"] == 1

    print("TelemetryEvent serialization: OK")

    # ------------------------------------------------------------------
    # Aggregate
    # ------------------------------------------------------------------

    aggregate = TemperatureAggregate(
        aggregate_id="aggregate-test-001",
        device_id="device-001",
        window_start=datetime.now(timezone.utc),
        window_end=datetime.now(timezone.utc),
        event_count=10,
        temperature_sum=255.0,
        temperature_min=22.0,
        temperature_max=29.0,
        temperature_avg=25.5,
        last_event_timestamp=datetime.now(timezone.utc),
    )

    assert aggregate.event_count == 10
    assert aggregate.temperature_avg == 25.5

    print("TemperatureAggregate validation: OK")

    # ------------------------------------------------------------------
    # Worker metric
    # ------------------------------------------------------------------

    metric = WorkerMetric(
        worker_id="worker-1",
        timestamp=datetime.now(timezone.utc),
        messages_processed=100,
        messages_failed=2,
        events_per_second=20.0,
        processing_latency_ms=4.5,
        partitions_assigned=4,
        active_windows=3,
        bytes_processed=20480,
        status="running",
    )

    assert metric.worker_id == "worker-1"
    assert metric.messages_processed == 100

    print("WorkerMetric validation: OK")

    # ------------------------------------------------------------------
    # Checkpoint
    # ------------------------------------------------------------------

    checkpoint = CheckpointMetadata(
        checkpoint_id="checkpoint-001",
        worker_id="worker-1",
        created_at=datetime.now(timezone.utc),
        state_path="data/checkpoints/checkpoint-001",
        event_count=100,
        topic="telemetry",
        partitions=[0, 1, 2, 3],
        offsets={
            "telemetry-0": 25,
            "telemetry-1": 25,
            "telemetry-2": 25,
            "telemetry-3": 25,
        },
        state_size_bytes=4096,
    )

    assert checkpoint.checkpoint_id == "checkpoint-001"
    assert checkpoint.event_count == 100

    print("CheckpointMetadata validation: OK")

    # ------------------------------------------------------------------
    # Backwards-compatible aliases
    # ------------------------------------------------------------------

    assert Aggregate is TemperatureAggregate
    assert Checkpoint is CheckpointMetadata

    print("Model aliases: OK")

    # ------------------------------------------------------------------
    # Invalid payload test
    # ------------------------------------------------------------------

    invalid_payload = dict(payload)
    invalid_payload["humidity"] = 150.0

    try:
        TelemetryEvent.model_validate(invalid_payload)
    except Exception:
        pass
    else:
        raise AssertionError("Invalid humidity was accepted")

    print("Invalid telemetry validation: OK")

    print("-" * 60)
    print("StreamForge models self-test: OK")


if __name__ == "__main__":
    run_self_test()